### ISSUE TITLE
Cheat menu Crash

### ISSUE THREAD

**Issue by gnmyt** [ABurgGames/CarrotQuest#1]
**Describe the bug**
Program crashing in cheat menu

**Reproduceing**
Open cheat menu, type a cheat without a multiplier, press space, press enter

**Expected behavior**
Program not crashing

**OS**
Linux

**Comment by HazDu** [comment]
Thanks for the Bug report I'm already on reprogamming the cheat menu. The bug will be fixed in the next update!
